const CANVAS_HEIGHT = 768;
const CANVAS_WIDTH = 1280;
const NUMBER_OF_TILES_IN_ROW = 20;
const TILE_SIZE = CANVAS_WIDTH/NUMBER_OF_TILES_IN_ROW;

const INCREASE_ENEMY_COUNT = 1;
const MAX_ENEMY_KILLS = 20;
const ENEMY_KILL_REWARD = 25;
const ENEMIES_OFFSET = 150;

const BUILDING_COST = 50;
const BUILDING_AMMO = 10;
const AMMO_DAMAGE = 10;

//Building
const BUILDING_Y_OFFSET = -80;
const BUILDING_FRAMES = 19;
const BUILDING_RADIUS = 250;

//Enemy
const ENEMY_WIDTH = 100;
const ENEMY_HEIGHT = 100;
const ENEMY_RADIUS = 50;
const ENEMY_HEALTH = 100;
const ENEMY_SPEED = 2;
const ENEMY_FRAMES = 7;

//Projectile
const PROJECTILE_RADIUS = 10;
const PROJECTILE_SPEED = 5;